server:
  port: 8888

spring:
  application:
    name: kubbi-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/freeChildren/kubbi-config-repertory.git
          search-paths: /config-repo
          username:  15915787046@139.com
          password:  KeGaoFei@2013
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://freeChildren:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}