eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    

spring:
  application:
    name: kubbi-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/freeChildren/kubbi-config-repertory.git
          search-paths: /config-repo
          username: 
          password: 
server:
  port: 8888